[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
liars_dice = "AZrqTVywNJhAvGvComNiHVbmUCVEyJnhfcKtGURdmG2B"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
