[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
liars_dice = "AZrqTVywNJhAvGvComNiHVbmUCVEyJnhfcKtGURdmG2B"

[programs.devnet]
liars_dice = "3TgXhxUPSweZi49FSByfXAXXxnvoFJaui9kaZxfuUTSu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
